name: e2e-tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  build-auto-instrumentation:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-22.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup image cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/docker-images
          key: docker-images-otel-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-images-otel-${{ runner.os }}-
      - name: Build auto-instrumentation
        run: |
          mkdir -p /tmp/docker-images
          DOCKER_BUILDKIT=1 docker build -t otel-go-instrumentation:latest .
          docker save otel-go-instrumentation:latest -o /tmp/docker-images/otel-go-instrumentation.tar

  build-sample-app:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-22.04-arm]
        library: ["autosdk", "nethttp", "nethttp_custom", "gin", "databasesql", "grpc", "otelglobal", "kafka-go"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup image cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/docker-images
          key: docker-images-sample-${{ matrix.library }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-images-sample-${{ matrix.library }}-${{ runner.os }}-
      - name: Build sample app
        run: |
          mkdir -p /tmp/docker-images
          if [ -f "./internal/test/e2e/${{ matrix.library }}/build.sh" ]; then
            echo ">>> Building ${{ matrix.library }} sample app using build.sh script <<<"
            ./internal/test/e2e/${{ matrix.library }}/build.sh -t sample-app-${{ matrix.library }}:latest
          else
            echo ">>> Building ${{ matrix.library }} sample app directly with Dockerfile <<<"
            DOCKER_BUILDKIT=1 docker build -t sample-app-${{ matrix.library }}:latest ./internal/test/e2e/${{ matrix.library }}
          fi
          docker save sample-app-${{ matrix.library }}:latest -o /tmp/docker-images/sample-app-${{ matrix.library }}.tar

  kubernetes-test:
    needs:
      - build-auto-instrumentation
      - build-sample-app
    strategy:
      matrix:
        k8s-version: ["v1.26.0"]
        library: ["autosdk", "nethttp", "nethttp_custom", "gin", "databasesql", "grpc", "otelglobal", "kafka-go"]
        runner: [ubuntu-latest, ubuntu-22.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
        with:
          version: v3.9.0
      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
          kubectl_version: ${{ matrix.k8s-version }}
      - name: Check kind
        run: |
          kubectl cluster-info --context kind-chart-testing
          kubectl get node
          docker ps -a --filter label=io.x-k8s.kind.cluster=chart-testing
      - name: Restore auto-instrumentation image
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/docker-images
          key: docker-images-otel-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-images-otel-${{ runner.os }}-${{ github.sha }}
            docker-images-otel-${{ runner.os }}-
      - name: Restore sample app image
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/docker-images
          key: docker-images-sample-${{ matrix.library }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-images-sample-${{ matrix.library }}-${{ runner.os }}-${{ github.sha }}
            docker-images-sample-${{ matrix.library }}-${{ runner.os }}-
      - name: Load images into Docker
        run: |
          # Load the cached images
          mkdir -p /tmp/docker-images
          if [ -f "/tmp/docker-images/otel-go-instrumentation.tar" ]; then
            docker load -i /tmp/docker-images/otel-go-instrumentation.tar
          else
            echo "Auto-instrumentation image not found in cache!"
            exit 1
          fi
          
          if [ -f "/tmp/docker-images/sample-app-${{ matrix.library }}.tar" ]; then
            docker load -i /tmp/docker-images/sample-app-${{ matrix.library }}.tar
            docker tag sample-app-${{ matrix.library }}:latest sample-app:latest
          else
            echo "Sample app image not found in cache!"
            exit 1
          fi
      - name: Load images into Kind
        run: |
          kind load docker-image otel-go-instrumentation:latest --name chart-testing
          kind load docker-image sample-app:latest --name chart-testing
      - name: Add Dependencies
        shell: bash
        run: |
            helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: 'open-telemetry/opentelemetry-helm-charts'
          path: opentelemetry-helm-charts
      - name: Helm install collector
        run: |
          if [ -f ./internal/test/e2e/${{ matrix.library }}/collector-helm-values.yml ]; then
            helm install test -f ./internal/test/e2e/${{ matrix.library }}/collector-helm-values.yml opentelemetry-helm-charts/charts/opentelemetry-collector
          else
            helm install test -f .github/workflows/e2e/k8s/collector-helm-values.yml opentelemetry-helm-charts/charts/opentelemetry-collector
          fi
      - name: check collector status
        # The loop is needed if the pod is not created yet
        # once https://github.com/kubernetes/kubectl/issues/1516 is fixed we can remove the loop
        run: |
          while : ; do
            kubectl get pod/test-opentelemetry-collector-0 && break
            sleep 5
          done
          kubectl wait --for=condition=Ready --timeout=60s pod/test-opentelemetry-collector-0
      - name: start sample job
        run: |
          kubectl -n default create -f .github/workflows/e2e/k8s/sample-job.yml
      - name: check job status
        id: job-status
        run: |
          kubectl wait --for=condition=Complete --timeout=60s job/sample-job
      - name: copy telemetry trace output
        run: |
          kubectl cp -c filecp default/test-opentelemetry-collector-0:tmp/trace.json ./internal/test/e2e/${{ matrix.library }}/traces-orig.json
          rm -f ./internal/test/e2e/${{ matrix.library }}/traces.json
        if: always() && steps.job-status.outcome == 'success'
      - name: print auto-instrumentation logs
        run: |
          kubectl logs -l app=sample -c auto-instrumentation --tail=300
          exit 1
        if: always() && steps.job-status.outcome == 'failure'
      - name: Setup BATS
        if: always() && steps.job-status.outcome == 'success'
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
      - name: verify output and redact to traces.json
        run: |
          bats ./internal/test/e2e/${{ matrix.library }}/verify.bats
        if: always() && steps.job-status.outcome == 'success'
